services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Causal\IgLdapSsoAuth\:
    resource: "../Classes/*"
    exclude: "../Classes/Domain/Model/*"

  #TODO@gm: fix misses sources attribute
#  Causal\IgLdapSsoAuth\Property\TypeConverter\ConfigurationConverter:
#    tags:
#      name: extbase.type_converter
